[package]
name = "rasar"
version = "0.1.5"
authors = ["Zerthox <zerthox@gmail.com>"]
description = "Asar packager & extractor written in Rust."
edition = "2018"

[dependencies]
clap = "2.33"
serde_json = "1.0"
glob = "0.3"