[package]
name = "rasar"
version = "0.1.0"
authors = ["Zerthox <zerthox@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
serde_json = "1.0.44"
